name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3 # ソースコード取得(チェックアウト)

      - name: Set up JDK 17
        uses: actions/setup-java@v3 # Javaの実行環境を作成
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Test # ビルドとテスト
        run: ./gradlew build # コマンドラインにてテストとビルドを実行
