name: Network Configuration

on:
  workflow_run:
    workflows: ["Build & Test CI"]
    types:
      - requested

jobs:
  network_configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Set up network configuration
        run: echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf
