name: Build & Test CI # ワークフロー名

on:
  pull_request:  # ワークフローを開始するイベント名
    branches:
      - develop

jobs: # ワークフローで実行されるジョブ群
  code-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Check code formatting
        run: ./gradlew checkstyleMain checkstyleTest
