name: Build & Test CI # ワークフロー名

on: push # ワークフローを開始するイベント名

jobs: # ワークフローで実行されるジョブ群
  build-and-test: # ジョブID
    runs-on: ubuntu-latest # ジョブが実行されるマシンの種類
    steps: # ジョブで実行されるステップ群
      - name: Checkout
        uses: actions/checkout@v3 # ソースコード取得(チェックアウト)
      - name: Set up JDK 17
        uses: actions/setup-java@v3 # Javaの実行環境を作成
        with:
          java-version: '17'
          distribution: 'adopt'
      #- name: Validate Gradle wrapper
      #  uses: gradle/wrapper-validation-action@v1 # チェックサムの妥当性を検証
      - name: Build with Test # ビルドとテスト
        run: ./gradlew build # コマンドラインにてテストとビルドを実行
